[package]
name = "tool_msvc"
version = "0.52.0"
edition = "2021"
publish = false

[dependencies]
lib = { package = "tool_lib", path = "../lib" }
windows-sys = { path = "../../libs/sys", features = ["Win32_System_LibraryLoader"] }
